### ISSUE TITLE
Data structures category?

### ISSUE THREAD

**Issue by TomerAberbach** [parro-it/awesome-microlibs#69]
I was thinking of adding [`quetie`](https://github.com/TomerAberbach/quetie) (a very small queue implementation) here, but I wasn't sure what section it should go in. It's implemented using arrays so maybe that section?

Otherwise, maybe a new data structures section? Might be nice to collect all the small implementations :smile:

**Comment by parro-it** [comment]
I like the idea of a data structures section, thank you!

**Comment by parro-it** [comment]
I had a look at quetie, seems really nice and high quality, if you write a PR I'll add it quickly...
